version: '3.1'


services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dihset
      MONGO_INITDB_ROOT_PASSWORD: 170798

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dihset
      ME_CONFIG_MONGODB_ADMINPASSWORD: 170798

  api:
    build: ./api
    restart: always
    ports:
      - 8080:8080
    environment:
      DB_USER: dihset
      DB_PASSWORD: 170798
      DB_NAME: notification-service
